version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: university-db
    environment:
      POSTGRES_USER: shaxzodbek
      POSTGRES_PASSWORD: shox777
      POSTGRES_DB: miniproj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
